#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo-runner"
name = "Forgejo Runner"
description.en = "Runner for Forgejo"
description.fr = "Runner pour Forgejo"

version = "3.5.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://forgejo.org/docs/next/admin/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.token]
    ask.en = "Enter the token, that can be retrieved at this location: https://forgejo.domain.tld/admin/actions/runners"
    ask.fr = "Ce token peut être récupéré à cet emplacement : https://forgejo.domain.tld/admin/actions/runners"
    type = "string"
    example = "xxxx"

    [install.forgejo_url]
    ask.en = "Please enter Forgejo instance URL"
    ask.fr = "Veuillez entrer l'URL de votre instance Forgejo"
    type = "string"
    example = "https://domain.tld/forgejo"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v3.5.1/forgejo-runner-3.5.1-linux-amd64"
        amd64.sha256 = "e2f36aa8149a0e883b5713398aa185c88a827fc0527d5cd2e2b05b88c9ba0b36"
        arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v3.5.1/forgejo-runner-3.5.1-linux-arm64"
        arm64.sha256 = "74f83b7ff122422d2b6b9841e61a453305ca1bed5287987d026cb9645ab9a1d9"
        in_subdir = false
        extract = false
        rename = "forgejo-runner"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = "ca-certificates, git, curl, tar"

    extras.docker.repo = "https://download.docker.com/linux/debian bullseye stable"
    extras.docker.key = "https://download.docker.com/linux/debian/gpg"
    extras.docker.packages = "docker-ce, docker-ce-cli, containerd.io"
